version: "3.8"
services:
  mc:
    image: "itzg/minecraft-server:java25"
    container_name: mc-server
    ports:
      - "25565:25565" # Java Edition
    environment:
      VERSION: 26.1.1
      EULA: "TRUE"
      TYPE: FABRIC
      MODE: CREATIVE
      FORCE_GAMEMODE: "TRUE"
      ONLINE_MODE: "FALSE"
      ENABLE_WHITELIST: "FALSE" # Let SimpleAuth handle authentication
      OPS: Dad # Your admin user here
      MEMORY: 6G
      # Fabric specific
      FABRIC_LOADER_VERSION: 0.18.6
      # Auto-remove old mods on update
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_INCLUDE: "SimpleAuth*.jar"
      # Auto-download mods
      MODS: https://github.com/status-machina/SimpleAuth/releases/latest/download/SimpleAuth-1.1.0.jar
    volumes:
      - "mc_data:/data"
    stdin_open: true
    tty: true

volumes:
  mc_data:
